services:
  - type: web
    name: ccas-system
    env: node
    buildCommand: npm install --build-fram-source
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOST
        value: 0.0.0.0
